name: Deploy Python Function to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'Azure' # Points to your Azure directory
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'rhel-ztp-composer-app' # Replace with your target Function App name
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNC_PUBLISH_PROFILE }}